### ISSUE TITLE
Support @tanstack/react-query v5

### ISSUE THREAD

**Issue by rliljest** [dotansimha/graphql-code-generator-community#318] opened 2023-03-28 21:43 UTC
**Is your feature request related to a problem? Please describe.**

New features are coming out in [@tanstack/react-query@5](https://github.com/TanStack/query/releases) that our team is excited about using, but currently generated `react-query` code is not compatible

**Describe the solution you'd like**

Ideally it would be nice to support both v4 and v5, but I'm unsure how complicated that would be. The [v4 to v5 migration guide](https://tanstack.com/query/v5/docs/react/guides/migrating-to-v5) lists the differences. The first change: `Supports a single structure, one object` is one that currently generated code fails on, but the generated code can be updated to support both v4 and v5, even before officially supporting v5.

We would need something similar to the current `legacyMode` flag to enable/disable v5. Maybe instead of `legacyMode`, we could have a `reactQueryVersion` flag that could either be "3", "4", or "5"? Or maybe only "4" and "5": I'm unsure how many projects are using graphql-codegen and still using the legacy "3" version.

**Describe alternatives you've considered**

The main alternative would be to not use v5 and still stay on v4. This would not be ideal: there are some TypeScript fixes in v5 that we have been waiting on, including a TypeScript fix when using infinite queries and the `select` option.

**Additional context**

react-query v5 is still in a pre-release stage, so the API is not 100% finalized. The `errorType` type option might still be useful, but v5 does update the default Error type from `unknown` to `Error`, which I think is one of the reasons why the `errorType` option was added in the first place.

Looking at the migration guide, I'm guessing there will also be significant changes to the generated [infinite query](https://tanstack.com/query/v5/docs/react/guides/migrating-to-v5#infinite-queries-now-need-a-initialpageparam) code. 

UPDATE: One more feature I see in react-query v5 that would be fantastic to include: support for [useSuspenseQuery](https://tanstack.com/query/v5/docs/react/reference/useSuspenseQuery) and [useSuspenseInfiniteQuery](https://tanstack.com/query/v5/docs/react/reference/useSuspenseInfiniteQuery). This could be similar to the `addInfiniteQuery` option: something like `addSuspenseQuery`

**Comment by TkDodo** [comment] 2023-09-14 18:12
Let me know if I can help - v5 release candidate is coming soon

**Comment by saihaj** [comment] 2023-09-25 21:40
what are the changes needed here for us to support? If someone wants to send in PRs to add support I am happy to review and get it released!

**Comment by TkDodo** [comment] 2023-09-26 06:04
rc is here: https://github.com/TanStack/query/releases/tag/v5.0.0-rc.1

for necessary changes, see the upgrade guide: https://tanstack.com/query/v5/docs/react/guides/migrating-to-v5

**Comment by neil585456525** [comment] 2023-09-26 08:01
@saihaj I can work on this topic, since our team also use react query + gql codegen. Can you kindly assign this task to me?

**Comment by neil585456525** [comment] 2023-09-27 14:26
After investigating the plugin code structure, I found that although the generated code logic is spread across different fetcher implementations, the parts that integrate react-query are surprisingly identical! In my design, I would create a mapping function for each react-query method (useQuery, useMutation, and so on) which can be used across all fetchers. This should allow us to easily switch between different versions without altering our plugin codebase too much. Additionally, it will help ensure that future fetchers can be implemented with the functionality to support different versions more easily.

**Comment by neil585456525** [comment] 2023-10-02 07:39
@rliljest @saihaj 
Please review my pr, you can use my reproduce-repo to check. Feel free to leave any comment and feedback about it.

**Comment by saihaj** [comment] 2023-10-25 01:03
Thank you very much @neil58545652 @rliljest @TkDodo !
[@graphql-codegen/typescript-react-query@6.0.0](https://github.com/dotansimha/graphql-code-generator-community/releases/tag/release-1698195675195)

**Closed by saihaj** 2023-10-25 01:03 UTC
Labels: enhancement

**Comment by dohomi** [comment] 2023-11-08 02:43
Great feature, works like a charm. Would be great to add `reactQueryVersion` to the official docs.

**Comment by dohomi** [comment] 2023-11-09 03:22
Currently the v6 feature does not support preset `import-types`.

```ts
    'src/utils/__generated__/graphql.ts': {
      documents: ['src/**/*.gql'],
      plugins: ['typescript-react-query'],
      preset: 'import-types',
      presetConfig: {
        typesPath: './types',
        importTypesNamespace: 'SchemaTypes'
      },
    (...)
```

This is how the geneated file looks like in v6

<img width="728" alt="Screenshot 2023-11-09 at 11 16 56" src="https://github.com/dotansimha/graphql-code-generator-community/assets/489221/e3aa24a3-fdd1-42ec-925c-50aaacd3520c">


And this is the correct behaviour in v5, all types have the correct type name

<img width="524" alt="Screenshot 2023-11-09 at 11 19 28" src="https://github.com/dotansimha/graphql-code-generator-community/assets/489221/65ec9beb-8c22-417d-8626-a06c65cd7ce2">

**Comment by ceefour** [comment] 2023-12-18 14:35
Agree with @dohomi , this needs to be documented in the official https://the-guild.dev/graphql/codegen/plugins/typescript/typescript-react-query 

@TkDodo I want to contribute, but I can't find where to add it?
